### ISSUE TITLE
64MB Hack

### ISSUE THREAD

**Issue by fook42** [Acill/A4000RevB#3]
no real issue.. but maybe a request for an adaption:
is it possible to include the necessary changes for the 64MB Hack in order to install 4* 16MB Modules to the Mainboard?
Maybe the changes can be "selectable" via additional jumpers?
(see: chuckys page http://wordpress.hertell.nu/?p=303 ... or http://www.nightfallcrew.com/25/02/2016/commodore-amiga-4000-hack-to-handle-64mb-of-fast-memory )

**Comment by Acill** [comment]
I personally do not like this hack. The goal of this project was to create
a clone for repairs of current motherboards. If anyone would like to do
this they are welcome. I just ask that it get clearly documented if done
and uploaded.
